from enum import Enum

class AvailableHouse(Enum):
    ONE_ROOM_APPARTMENT = "ONE_ROOM_APPARTMENT" 
    TWO_ROOM_APPARTMENT = "TWO_ROOM_APPARTMENT"
    FOUR_ROOM_PENTHOUSE = "FOUR_ROOM_PENTHOUSE"
    FIVE_ROOM_MANSION = "FOUR_ROOM_PENTHOUSE"